### ISSUE TITLE
How can I protect my paid android app from sharing?

### ISSUE THREAD

**Issue by merbin2012** [mobilino/Phonegap-android-license-plugin#5] opened 2016-12-05 17:44 UTC
After searching to the internet I found the LVL is used for protecting the app from sharing(Checking license is valid or not), but here I don't know how to use this? any time it shows random values.

**Comment by mobilino** [comment] 2016-12-06 11:02
this is a duplicate of #4 
This plugin deliberately does not validate but only extracts the license data. A working but poor way to use the LVL result would be to only look at the "responsecode".

**Comment by merbin2012** [comment] 2016-12-06 15:20
Then what is the purpose of this plugin?

**Comment by mobilino** [comment] 2016-12-07 13:47
I tried to explain this in the README: "[...] You can use this information to send it to your server for license verification and only grand those users access whose license information is valid.
[...] Please note that you do NOT need to include you Public Key in the app since you will validate the license response on your server." 
And again in #4 : "as stated in the readme this plugin only extracts the license information. This is useful if you want to validate the license information on your server. (Which is much more secure then validating it in the app itself.) Since there is no coding to validate the license information in the app itself, there is also no need to ship your public key as part of the app.
If you app does not communicate with a server this plugin is not suitable for you."

I feel like this exactly answers your question concerning the "purpose". However, obviously you do not think so. Consequently please elaborate your question in more detail.

**Comment by merbin2012** [comment] 2016-12-08 18:46
I want to create a paid app using cordova and I want to validate the user using paid app or shared app. Can I used for it? If yes, can you please give me more code about it server code also need(little).

**Comment by mobilino** [comment] 2016-12-10 12:42
The link to the .php server side code for validation is included in the readme. 
If you want to use this plugin - without any server side code - you may just check the "responsecode" of this plugin.
However, if you want to validate the response in your app itself you may write your own plugin.

Sorry, I am not aware of any other way. Since all this has already been said here or in #4. I will close this issue.

**Closed as completed by mobilino** 2016-12-10 12:42 UTC
